# Generated by Django 2.1.7 on 2019-03-19 21:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('used_events', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('super_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SuperGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('used_events', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Group')),
            ],
        ),
    ]
